### ISSUE TITLE
problem with the powerSpectrumEns

### ISSUE THREAD

**Issue by JianghuiDu** [nickmckay/GeoChronR#24]
I found a problem with this function and I traced it back to the redfit function in the dplR package. Though redfit is supposed to handle unevenly spaced time series but whenever the actual data is unevenly spaced the function fails and creates an error saying "REAL() can only be applied to a 'numeric', not a 'integer'". I checked that the input were indeed numeric, not sure why it was considered integer by the function. I tested redfit separately outside the GeoChronR package, it didn't work on non evenly spaced time series.

**Comment by nickmckay** [comment]
Hmm, that's interesting. Flagging @CommonClimate who was tinkering with this.

**Comment by CommonClimate** [comment]
Hi Jianghui, 
I am not a big fan of Redfit; I included it because it's a commonly used method, but everything I find out about it makes me more wary. I know very little about its R implementation and I suggest you contact Andy Bunn at WWU, who coded it up. We're also working on  a wavelet-based method ("nuspectral"), which should hopefully be a viable alternative to redfit.
I hope this helps,
Julien

**Comment by CommonClimate** [comment]
Hi Jianghui,
were you able to resolve this to your satisfaction? Is it OK to close the issue?
Best,
Julien

**Comment by JianghuiDu** [comment]
I've found another way. Thanks!
