### ISSUE TITLE
extracting PCAens loadings and time series (scores)

### ISSUE THREAD

**Issue by istvan60** [nickmckay/GeoChronR#47]
It would be good and important enhancement to the package to be able to extract the coordinates of the envelope curves and the PC time series themselves from the `pcaEns` output for further analysis/comparison with other climate records (black lines and grey backgrounds in the [summary plots](https://nickmckay.github.io/GeoChronR/articles/PCA.html).

I tried to do that from the `plotPcaEns` output itself for the sake of the example following the code from [here](https://nickmckay.github.io/GeoChronR/articles/PCA.html) as:

`PCs=as.list.data.frame(pcout$PCs)`
`PC1=PCs[1:104,1,1:1000]` where there were 520 time points with 5 yr binning (=104) and 8 PCs extracted with `n.ens=1000`. This gave a large three dim array with the first dim the "time points" (1:104), the second the number of PCs (1:8) and the number of ensemble members(1:1000)
This should be the PC time series of PC1, but I was not able to determine the primary time series (median, avg?) that correspond to the plot below:

<img width="596" alt="Screenshot 2020-10-19 at 23 48 24" src="https://user-images.githubusercontent.com/20128185/96515432-970adb00-1265-11eb-9617-4e9cc83eac16.png">

**Comment by nickmckay** [comment]
So this functionality actually already exists, but isn't shown in the example. I've cleaned up the output a bit and added the example to the vignette in the development version, so that should be live one the next version update. 

In the meantime, you can extract a list with the quantiles using this command:

`quantileData <- plotTimeseriesEnsRibbons(X = pcout$age,Y = pcout$PCs[,1,],export.quantiles = TRUE)`

check out `?plotTimeseriesEnsRibbons` for details on `export.quantiles`.

Note that on the next version upgrade I've changed the output to be a tibble, rather than a list, which should be more convenient.
