### ISSUE TITLE
formal argument "acc.mean" matched by multiple actual arguments

### ISSUE THREAD

**Issue by sofiakje** [nickmckay/GeoChronR#56]
Hi Nick,

I want to build an age-depth model for a sediment core with changing sedimentation rate. I try adding a boundary and assign the core different accumulation priors above and below the boundary, but it doesn't work. I can add the boundary, but not set different acc.mean for the different stratigraphic units.

This is the code I run:
D = runBacon(D,d.min=0,d.max=196,rotate.axes=TRUE,boundary=26,acc.mean=c(20,50))

And this is the error I get: 
Error in rbacon::Bacon(core = site.name, coredir = bacon.dir, thick = thick,  : 
  formal argument "acc.mean" matched by multiple actual arguments

Any thoughts on what is going wrong?

Thanks!
Sofia

**Comment by CommonClimate** [comment]
Hi Sofia,
I'll take a stab at this even though I'm not the R programmer on the team... From the `rbacon::Bacon()` documentation, it seems that one way to recognize that there are changes in sedimentation rate is to specify a parameter called `hiatus.depths`, which the geoChronR API should allow you to pass to Bacon. Can you give that a try and see what happens?
Julien

**Comment by nickmckay** [comment]
A bit more on this, and sorry to make Julien wade in a bit here. Most bacon parameters can be passed directly through `runBacon` to bacon, but `acc.mean` is one of the exceptions because of some additional work that geoChronR does. So to set `acc.mean`, use the parameter `bacon.acc.mean = c(20,50)`. You should be ok with two values there. 

The other parameter that works like this is the `thick` parameter, for which you'd need `bacon.thick`. Complete details of the parameters are available in the help, or [documentation, which is here](https://nickmckay.github.io/GeoChronR/reference/runBacon.html)

**Comment by CommonClimate** [comment]
Yes, what he said !

**Comment by sofiakje** [comment]
Yes, that worked perfectly! Good to know about the exceptions - I'll remember that for next time I run into similar problems. Thank you!
